"""user_table_update

Revision ID: 19661ec2e6dc
Revises: b232fbddb841
Create Date: 2023-02-17 16:35:30.375679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19661ec2e6dc'
down_revision = 'b232fbddb841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
