"""Users Events

Revision ID: 785cfe69a9aa
Revises: c0fe698414db
Create Date: 2023-02-24 16:43:52.688383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785cfe69a9aa'
down_revision = 'c0fe698414db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_creator', sa.Integer(), nullable=True),
    sa.Column('date_event', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loscut', sa.String(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('online', sa.BOOLEAN(), nullable=True),
    sa.Column('privacy', sa.BOOLEAN(), nullable=True),
    sa.Column('venue', sa.TEXT(), nullable=True),
    sa.Column('id_master', sa.Integer(), nullable=True),
    sa.Column('connected_players_count', sa.Integer(), nullable=True),
    sa.Column('game_status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_master'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['game_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_game_events')
    op.drop_table('game_events')
    # ### end Alembic commands ###
