"""Game Campaign

Revision ID: 83efa505440d
Revises: e7cd5f4bce1f
Create Date: 2023-03-01 15:52:43.870650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83efa505440d'
down_revision = 'e7cd5f4bce1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_events_id_game_campaign_fkey', 'game_events', type_='foreignkey')
    op.drop_table('game_campaigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_campaigns',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='game_campaigns_pkey')
    )
    op.create_foreign_key('game_events_id_game_campaign_fkey', 'game_events', 'game_campaigns', ['id_game_campaign'], ['id'])
    # ### end Alembic commands ###
