"""user_verified_table

Revision ID: c0fe698414db
Revises: dbc7f0de7a03
Create Date: 2023-02-22 15:30:32.951273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fe698414db'
down_revision = 'dbc7f0de7a03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_verification_email', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_verification_email', type_='unique')
    # ### end Alembic commands ###
