"""Game Campaign

Revision ID: e7cd5f4bce1f
Revises: 785cfe69a9aa
Create Date: 2023-03-01 14:54:22.362704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cd5f4bce1f'
down_revision = '785cfe69a9aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_campaigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_events', sa.Column('id_game_campaign', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_events', 'game_campaigns', ['id_game_campaign'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_events', type_='foreignkey')
    op.drop_column('game_events', 'id_game_campaign')
    op.drop_table('game_campaigns')
    # ### end Alembic commands ###
